services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Vienna
    volumes:
      - /home/maksymilian/radarr/data:/config
      - /home/maksymilian/maksymilian-share/plex/movies:/movies 
      - /home/maksymilian/data:/downloads 
    ports:
      - 7878:7878
    restart: unless-stopped