services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Vienna
    volumes:
      - /home/maksymilian/sonarr/data:/config
      - /home/maksymilian/maksymilian-share/plex/tv:/tv #optional
      - /home/maksymilian/data:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped