services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Vienna
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /home/maksymilian/plex/data:/config
      - /home/maksymilian/maksymilian-share/tv:/tv
      - /home/maksymilian/maksymilian-share/movies:/movies
    restart: unless-stopped